spring:
  application:
    name: "vpn-control-panel-backend"
  datasource:
    url: jdbc:postgresql://minikube:30001/database
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



vpn:
  guest:
    ip-range:
      start: 10.8.0.20
      end: 10.8.0.255
    subnet: 255.255.255.0
  admin:
    ip-range:
      start: 10.8.0.10
      end: 10.8.0.19
    subnet: 255.255.255.0

certificate:
  operations:
    allowed: true