spring:
  application:
    name: "vpn-control-panel-backend"
  datasource:
    url: jdbc:postgresql://minikube:30001/database
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



vpn:
  allowCertificateOperationsOnServer: false


certificate:
  operations:
    allowed: false% 