spring:
  application:
    name: "vpn-control-panel-backend"
  datasource:
    url: jdbc:postgresql://minikube:30001/database
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

firewall:
  client-rules-file: /home/haroun/nftables/per-client-rules.nft
  nft-config-file: /home/haroun/nftables/nftablse.conf

vpn:
  server: vpn.erisdev.io
  port: 1194
  ccd-directory: /home/haroun/openvpntest/ccd
  default-destination: 10.8.0.1
  guest:
    ip-range:
      start: 10.8.0.20
      end: 10.8.0.255
    subnet: 255.255.255.0
  admin:
    ip-range:
      start: 10.8.0.10
      end: 10.8.0.19
    subnet: 255.255.255.0
  agent:
    enabled: true
    status-path: /var/lib/openvpn/clients.json
    socket-path: /var/run/openvpn/agent.sock
    status-interval: 5
    status-mode: ssh # or 'file'
    ssh:
      user: vpnapp
      password: Didi1234
      host: 10.8.0.1
      port: 22




certificate:
  operations:
    allowed: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filterChainProxy: TRACE
